name: rive_playground_app
description: A playground for testing Rive animations

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Rive animation
  rive: ^0.13.0
  
  # Charts for timeline
  fl_chart: ^0.68.0
  
  # State management (optional, for better architecture)
  provider: ^6.1.0
  
  # Other useful packages
  flutter_animate: ^4.5.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add your Rive animation files here
  assets:
    - animations/